# Generated by Django 3.0.1 on 2020-01-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('videofile', models.FileField(upload_to='videos/', verbose_name='')),
                ('desc', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='currentProjectImages/', verbose_name='Image')),
                ('title', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.CurrentProject')),
            ],
        ),
    ]
