# Generated by Django 3.0.1 on 2020-01-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200128_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='videofile',
            field=models.FileField(upload_to='media/videos/', verbose_name=''),
        ),
    ]
