# Generated by Django 3.0.1 on 2020-01-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200128_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='videofile',
            field=models.FileField(upload_to='videos', verbose_name=''),
        ),
    ]
