# Generated by Django 3.0.1 on 2020-01-29 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
    ]
