# Generated by Django 3.0.1 on 2020-01-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200109_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='is_subscribed',
            field=models.BooleanField(default=False, max_length=1, null=True),
        ),
    ]
